# Generated by Django 3.1 on 2020-08-28 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nativelanguage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='native_language', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studyinglanguage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studying_language', to=settings.AUTH_USER_MODEL),
        ),
    ]
